#MPI 
N=2520
M=1920
process=( 4 9 16 25 36 49 64 81 100 )
loops=( 100 500 1000 2000 5000 ) ## 10000 15000 60000 100000)
size=( 1 )
for k in "${size[@]}";do
	for j in "${loops[@]}";do
		for i in "${process[@]}";do
			n=`echo $N*$k | bc`
			m=`echo $M*$k | bc`
			mpiexec -n $i -f machines build/conv -r $n -c $m -m $j -f  $1 -o $2 2> /dev/null 1>out
			echo Process: $i - Loops: $j - Size: $n x $m `cat out` >> MPI_Results
			echo ""
		done
		echo ""
		echo "" 
	done
done

rm out